### ISSUE TITLE
Error when using Serverless 3.0

### ISSUE THREAD

**Issue by filipemansano** [brefphp/extra-php-extensions#310]
After upgrading Serverless to version 3.0.0 I got the error below

```
Environment: linux, node 14.18.3, framework 3.0.0, plugin 6.0.0, SDK 4.3.0
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: Cannot read property 'bind' of undefined
    at new ServerlessPlugin (/home/filipemansano/konfetti/backend/source/vendor/bref/extra-php-extensions/index.js:45:33)
    at PluginManager.addPlugin (/usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:88:28)
    at /usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:135:33
    at Array.forEach (<anonymous>)
    at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:135:8)
    at Serverless.init (/usr/local/lib/node_modules/serverless/lib/serverless.js:137:30)
    at async /usr/local/lib/node_modules/serverless/scripts/serverless.js:529:7

```

version of bref and bref/extra-php-extensions used
```
"name": "bref/bref",
"version": "1.5.1",
"source": {
    "type": "git",
    "url": "https://github.com/brefphp/bref.git",
    "reference": "a627683f69416812dade926792bbd9ef2cc78f66"
},
```

```
"name": "bref/extra-php-extensions",
  "version": "0.11.21",
  "source": {
      "type": "git",
      "url": "https://github.com/brefphp/extra-php-extensions.git",
      "reference": "7fbb7241b8b9705b90d44298d382cf5d268c0911"
  },
```

**Comment by Nyholm** [comment]
Is this still an issue after we released #311 in 0.11.22?

**Comment by hmazter** [comment]
@Nyholm Testing with v0.11.23 does not give any error for `serverless package` at least

**Comment by Nyholm** [comment]
Thank you for confirming.
